# 外传篇.1-异常处理深度解析



![Slide01](外传篇.1-异常处理深度解析.assets/Slide01.PNG)



![Slide02](外传篇.1-异常处理深度解析.assets/Slide02.PNG)



![Slide03](外传篇.1-异常处理深度解析.assets/Slide03.PNG)



![Slide04](外传篇.1-异常处理深度解析.assets/Slide04.PNG)



![Slide05](外传篇.1-异常处理深度解析.assets/Slide05.PNG)

```cpp
#include <iostream>

using namespace std;

class Test 
{
public:
    Test() 
    {
        cout << "Test()"; 
        cout << endl;
    }
	
    ~Test() 
    {
        cout << "~Test()"; 
        cout << endl;
    }
};


int main()
{
    static Test t;
    
    throw 1;
	
    return 0;
}

```

**没有人处理异常，程序会被中止，情况取决于编译器，main函数里面的异常会被terminate进行处理**

![Slide06](外传篇.1-异常处理深度解析.assets/Slide06.PNG)



![Slide07](外传篇.1-异常处理深度解析.assets/Slide07.PNG)



![Slide08](外传篇.1-异常处理深度解析.assets/Slide08.PNG)

```cpp
#include <iostream>
#include <cstdlib>
#include <exception>

using namespace std;

void my_terminate()
{
    cout << "void my_terminate()" << endl;
    exit(1); // 会确保全局，静态的对象都会被析构掉；
}

class Test 
{
public:
    Test() 
    {
        cout << "Test()"; 
        cout << endl;
    }
	
    ~Test() 
    {
        cout << "~Test()"; 
        cout << endl;
    }
};


int main()
{
    set_terminate(my_terminate);
    
    static Test t;
    
    throw 1;
	
    return 0;
}

```

![Slide09](外传篇.1-异常处理深度解析.assets/Slide09.PNG)



![Slide10](外传篇.1-异常处理深度解析.assets/Slide10.PNG)

```cpp
#include <iostream>
#include <cstdlib>
#include <exception>

using namespace std;

void my_terminate()
{
    cout << "void my_terminate()" << endl;
    // exit(1);
    abort();
}

class Test 
{
public:
    Test() 
    {
        cout << "Test()"; 
        cout << endl;
    }
	
    ~Test() 
    {
        cout << "~Test()"; 
        cout << endl;
        
        throw 2;
    }
};


int main()
{
    set_terminate(my_terminate);
    
    static Test t;
    
    throw 1;
	
    return 0;
}

```

![Slide11](外传篇.1-异常处理深度解析.assets/Slide11.PNG)